CREATE TABLE HR.NOTICIA 
(	
  TITULO VARCHAR2(100 BYTE),
  AUTOR VARCHAR2(100 BYTE),
  FECHA DATE, 
  CONSTRAINT TITULO_PK PRIMARY KEY (TITULO)
);

INSERT INTO HR.NOTICIA VALUES('hola', 'ruben', sysdate);
COMMIT;

CREATE TABLE HR.COMENTARIO 
(	
  ID    NUMBER,
  TEXTO VARCHAR2(100 BYTE),
  AUTOR VARCHAR2(100 BYTE),
  NOTICIA_TITULO VARCHAR2(100 BYTE)
);

INSERT INTO HR.COMENTARIO(ID, TEXTO, AUTOR, NOTICIA_TITULO) VALUES (1, 'BIEN!!', 'JUAN', 'primera noticia');
COMMIT;

CREATE SEQUENCE cfab
START WITH 1
INCREMENT BY 1;

SELECT cfab.NEXTVAL FROM DUAL;